---
# tasks file for ansible-role-arc-frontend
#

- name: copy nordugrid.repo file
  template: src=nordugrid.repo.j2 dest=/etc/yum.repos.d/nordugrid.repo owner=root mode=0644 

- name: update all the things
  yum: name=* state=latest

- name: install Nordugrid ARC packages
  yum: name={{ item }} state=present
  with_items: packages | default({})

- name: copy arc.conf file
  template: backup=yes src=arc.conf.j2 dest=/etc/arc.conf owner=root mode=0644 

