---
# tasks file for ansible-role-arc-frontend
#

#- name: copy nordugrid.repo file
#  template: src=nordugrid.repo.j2 dest=/etc/yum.repos.d/nordugrid.repo owner=root mode=0644 
#
- name: install nordugrid repo
  yum: pkg=http://download.nordugrid.org/packages/nordugrid-release/releases/{{ arc_frontend_release }}/centos/el7/x86_64/nordugrid-release-{{ arc_frontend_release }}-1.el7.centos.noarch.rpm
  
- name: install nordugrid rpm key
  rpm_key: key=http://download.nordugrid.org/RPM-GPG-KEY-nordugrid state=present

- name: update all the things
  yum: name=* state=latest

- name: install Nordugrid ARC packages
  yum: name={{ item }} state=present
  with_items: arc_frontend_packages | default({})

- name: check if there's a nordugrid.repo.rpmnew
  stat: path=/etc/yum.repos.d/nordugrid.repo.rpmnew
  register: arc_frontend_rpmnew_stat

- name: Replace old nordugrid.repo
  command: mv /etc/yum.repos.d/nordugrid.repo.rpmnew /etc/yum.repos.d/nordugrid.repo
  when: arc_frontend_rpmnew_stat.stat.exists

- name: Template arc.conf file
  template: backup=yes src=arc.conf.j2 dest=/etc/arc.conf owner=root mode=0644 

- name: start and enable arc frontend services
  service: name={{ item }} state=started enabled=yes
  with_items: arc_frontend_packages | default({})
  when: arc_frontend_packages.0 != ""
